SportsStore/SportsStore/SportsStore.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IProductRepository repository;

        public AdminController(IProductRepository repo)
        {
            repository = repo;
        }
        

        public ActionResult Index()
        {
            return View(repository.Products);
        }

        public ViewResult Edit(int productId)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product,HttpPostedFileBase image=null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }
                repository.SaveProduct(product);
                TempData["message"] = string.Format("Zapisano {0} ", product.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        [HttpPost]
        public ActionResult Delete(int productId)
        {
            Product deleteProduct = repository.DeleteProduct(productId);
            if (deleteProduct != null)
            {
                TempData["message"] = string.Format("Usunięto {0}", deleteProduct.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

SportsStore/SportsStore/SportsStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 4;

        public ProductController(IProductRepository productParam)
        {
            this.repository = productParam;

        }

        public ViewResult List(string category,int page=1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repository.Products.Where(p=>category==null || p.Category==category)
                .OrderBy(p => p.ProductID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? repository.Products.Count() : 
                    repository.Products.Where(x=>x.Category==category).Count()
                },
                CurrentCategory=category
            };
            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product prod = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

    }
}

SportsStore/SportsStore/SportsStore.WebUI/Views/Admin/Edit.cshtml
@model SportsStore.Domain.Entities.Product

@{
    ViewBag.Title = "Edit" + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h1>Edycja @Model.Name</h1>
    </div>



@using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="panel-body">
    @Html.HiddenFor(x => x.ProductID)
        @foreach (var property in ViewData.ModelMetadata.Properties)
        {
            switch (property.PropertyName)
            {
                case "ProductID":
                case "ImageData":
                case "ImageMimeType":
                    //brak operacji
                    break;
                default:
            
                <div class="form-group">
                    <label>@(property.DisplayName ?? property.PropertyName)</label>
                    @if (property.PropertyName == "Description")
                    {
                        @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                    }
                    else
                    {
                        @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                    }
                    @Html.ValidationMessage(property.PropertyName)
                </div>
                break;
            }
        }
        <div class="form-group">
            <div style="position:relative;">
                <label>Zdjęcie</label>
                <a class='btn' href='javascript:;'>
                    Wybierz plik...
                    <input type="file" name="Image" size="40"
                        style="position:absolute;z-index:2;top:0;
left:0;filter:alpha(opacity=0);opacity:0;"onchange='$("#uplodad-file-info").html($(this).val());' />

                </a>
                <span class='label label-info' id="upload-file-info"></span>
            </div>
            @if (Model.ImageData == null)
            {
                <div class="form-control-static">Brak zdjęcia</div>
            }
            else
            {
                <img class="img-thumbnail" width="150" height="150"
                    src="@Url.Action("GetImage","Product",new{Model.ProductID})" />
            }
        </div>
       </div>
    
    <div class="panel-footer">
        <input type="submit" value="Zapisz" class="btn btn-primary"/>
    @Html.ActionLink("Anuluj i wróć do listy", "Index", null, new { @class = "btn btn-default" })
    </div>
}
    </div>

SportsStore/SportsStore/SportsStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Domain.Entities.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Wszystkie produkty</h3>
    </div>

<div class="panel-body">
<table class="table table-striped table-condensed table-bordered">
    <tr>
        <th>ID</th>
        <th>Nazwa</th>
        <th class="NumericCol">Cena</th>
        <th>Akcje</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ProductID</td>
            <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID })</td>
            <td class="NumericCol">@item.Price.ToString("c")</td>
            <td>
                @using (Html.BeginForm("Delete", "Admin"))
                {
                    @Html.Hidden("ProductID",item.ProductID)
                    <input type="submit" value="Usuń"/>
                }
            </td>
        </tr>
    }
</table>
    </div>
        <div class="panel-footer">
            @Html.ActionLink("Dodaj nowy produkt","Create",null, new{@class="btn btn-default"})
        </div>
    </div>